<?php

use App\Course;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CESubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subjects')->insert([
		//FIRST SEMESTER  FIRST YEAR CE
		[
		'sub'             =>'Eng 1',
		'sub_description' => 'Communication Arts 1',
		'units' => 3,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             =>'Fil 1',
		'sub_description' => 'Sining ng Pakikipagtalastasan',
		'units' => 3,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             =>'Hist 1',
		'sub_description' => 'Phil. History, Roots and Development',
		'units' => 3,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             =>'Math 17',
		'sub_description' => 'College Algebra',
		'year'            => 1,
		'units' => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             =>'Math 3',
		'sub_description' => 'Trigonometry',
		'units' => 3,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             =>'NSTP 1',
		'sub_description' => 'National Service Training Program 1',
		'units'           => 3,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             => 'PE 1',
		'sub_description' => 'Self-Testing Activities',
		'units' => 2,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             =>'Psycho 1',
		'sub_description' => 'General Psychology',
		'units' => 3,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		//SECOND SEMESTER FIRST YEAR CE
		[
		'sub'             => 'Chem 16',
		'sub_description' =>'General Chemistry 1',
		'units' => 5,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'Eng 2',
		'sub_description' =>'Communication Arts 2',
		'units' => 3,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'Math 51',
		'sub_description' =>'Calculus with Analytic Geometry 1',
		'units' => 6,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'NatSci 2',
		'sub_description' =>'Basic Biology',
		'units' => 3,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'NSTP 2',
		'sub_description' => 'National Service Training Program 2',
		'units'           => 3,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'PE 2',
		'sub_description' =>'Rythmic Activities',
		'units' => 2,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'Phys 21',
		'sub_description' =>'General Physics 1',
		'units' => 4,
		'year'            => 1,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		//FIRST SEMESTER  SECOND YEAR CE
		[
		'sub'             => 'Econ 101',
		'sub_description' => 'Principles of Economics with Taxation and Agrarian Reforms',
		'units' => 3,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             => 'Eng 3',
		'sub_description' => 'Speech and Oral Communication',
		'units' => 3,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             => 'ES 1',
		'sub_description' => 'Engineering Drawing 1',
		'units' => 2,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             => 'Human 1',
		'sub_description' => 'Humanities',
		'units' => 3,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             => 'Math 61',
		'sub_description' => 'Calculus with Analytic Geometry II',
		'units' => 6,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             => 'PE 3',
		'sub_description' => 'Fundamentals of Games and Sports',
		'units' => 2,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub'             => 'Phys 31',
		'sub_description' => 'General Physics 2',
		'units' => 4,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],

		[
		'sub'             => 'PolSci 1',
		'sub_description' => 'Politics & Governance w/ Philippine Constitution',
		'units' => 3,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],

		//SECOND YEAR SECOND SEMESTER CE
		[
		'sub'             => 'ES 2',
		'sub_description' => 'Computer Aided Drawing and Design I',
		'units' => 3,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'ES 40',
		'sub_description' => 'Fundamentals of Problem Solving & Programming',
		'units' => 3,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'Fil 2',
		'sub_description' => 'Pagbasa at Pagsulat sa Ibat Ibang Disiplina',
		'units' => 3,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'Lit 1',
		'sub_description' => 'Literature of the Philippines',
		'units' => 3,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'Math 71',
		'sub_description' => 'Calculus with Analytic Geometry III',
		'units' => 6,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'PE 4',
		'sub_description' => 'Creative and Recreational Activities',
		'units' => 2,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'Philo 1',
		'sub_description' => 'Logic',
		'units' => 3,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub'             => 'Phys 41',
		'sub_description' => 'General Physics 3',
		'units' => 4,
		'year'            => 2,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],

		//THID YEAR FIRST SEMESTER
		[
		'sub' => 'ES 51',
		'sub_description' => 'Differential Equations',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub' => 'ES 61',
		'sub_description' => 'Statics of Rigid Bodies',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub' => 'ES 71',
		'sub_description' => 'Probability and Statistics',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub' => 'ES 89',
		'sub_description' => 'Safety Management',
		'units' => 1,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub' => 'GE 41',
		'sub_description' => 'Elementary and Higher Surveying',
		'units' => 4,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub' => 'Geol 40',
		'sub_description' => 'Engineering Geology',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub' => 'ME 151',
		'sub_description' => 'Basic Mechanical Engineering',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],
		[
		'sub' => 'Rizal',
		'sub_description' => 'Life Works of Jose rizal',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,
		],

		//THIRD YEAR SECOND SEMESTER
		[
		'sub' => 'CE 100',
		'sub_description' => 'Intro to Environmental Engineering',
		'units' => 2,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'EE 123',
		'sub_description' => 'Elementary Electrical Engineering & Instrumentation',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'Eng 4',
		'sub_description' => 'Technical Writing',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'ES 55',
		'sub_description' => 'Numerical Methods',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'ES 62',
		'sub_description' => 'Dynamics of Rigid Bodies',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'ES 64',
		'sub_description' => 'Mechanics of Deformable Bodies',
		'units' => 3,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'GE 42',
		'sub_description' => 'Engineering Surveys',
		'units' => 4,
		'year'            => 3,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		//FOURTH YEAR FIRST SEMESTER
		[
		'sub' => 'CE 101',
		'sub_description' => 'Hydrology',
		'units' => 3,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'CE 111',
		'sub_description' => 'Building Design 1',
		'units' => 2,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'CE 120',
		'sub_description' => 'Highway Engineering',
		'units' => 3,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'CE 140',
		'sub_description' => 'Construction Materials and Testing',
		'units' => 4,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'CE 141',
		'sub_description' => 'Structural Theory 1',
		'units' => 4,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'ES 65',
		'sub_description' => 'Fluid Mechanics',
		'units' => 4,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'ES 90',
		'sub_description' => 'Engineering Economy',
		'units' => 3,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],

		//FOURTH YEAR SECOND SEMESTER
		[
		'sub' => 'CE 102',
		'sub_description' => 'Water Resource Engineering 1',
		'units' => 4,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'CE 112',
		'sub_description' => 'Building Design II',
		'units' => 2,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'CE 121',
		'sub_description' => 'Transportation Engineering',
		'units' => 3,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'CE 142',
		'sub_description' => 'Structural Theory II',
		'units' => 3,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'CE 144',
		'sub_description' => 'Design of Concrete Structures 1',
		'units' => 4,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'CE 150',
		'sub_description' => 'Geotechnical Engineering 1',
		'units' => 4,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'ES 56',
		'sub_description' => 'Advanced Engineering Mathematics for CE',
		'units' => 3,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],

		//FOURTH YEAR SUMMER
		[
		'sub' => 'CE 197',
		'sub_description' => 'CE Work Experience',
		'units' => 3,
		'year'            => 4,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => '',
		],


		//FIFTH YEAR FIRST SEMESTER
		[
		'sub' => 'CE 145',
		'sub_description' => 'Design of Concrete Structures II',
		'units' => 3,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'CE 147',
		'sub_description' => 'Design of Metal and Timber Structures',
		'units' => 4,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'CE 151',
		'sub_description' => 'Geotechnical Engineering II',
		'units' => 4,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'CE 181',
		'sub_description' => 'CE Elective I',
		'units' => 3,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'CE 198',
		'sub_description' => 'Construction Engineering & Project Management',
		'units' => 4,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],
		[
		'sub' => 'CE 199',
		'sub_description' => 'Civil Engineering Project',
		'units' => 3,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 1,

		],

		//FIFTH YEAR SECOND SEMESTER
		[
		'sub' => 'CE 103',
		'sub_description' => 'Water Resources Engineering II',
		'units' => 3,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'CE 182',
		'sub_description' => 'CE Elective II',
		'units' => 3,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'CE 183',
		'sub_description' => 'CE Elective III',
		'units' => 3,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'CE 184',
		'sub_description' => 'CE Elective IV',
		'units' => 3,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'CE 195',
		'sub_description' => 'CE Laws, Ethics, Bids, Contracts, & Specs',
		'units' => 3,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
		[
		'sub' => 'ES 91',
		'sub_description' => 'Engineering Management',
		'units' => 3,
		'year'            => 5,
		'course'          => Course::where('course_code','CE')->first()->id,
		'semester'        => 2,
		],
]);
    }
}
